export interface EmailTemplate {
  subject: string;
  htmlBody: string;
}

export const US_COLD_DAYS = [0, 3, 7, 12, 17, 23, 30];

export const US_COLD_SEQUENCE: EmailTemplate[] = [
  {
    subject: "KnowBe4 charges $0.65/seat. We charge $9 flat.",
    htmlBody: `<!DOCTYPE html><html><body style="margin:0;padding:0;font-family:Arial,sans-serif;background:#f4f4f4;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;margin:20px auto;border-radius:8px;"><tr><td style="padding:40px 40px 20px;"><h2 style="color:#1a1a1a;font-size:22px;margin:0 0 20px;">Hi [FirstName],</h2><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px;">[Company] is likely paying KnowBe4 per seat. We deliver the same enterprise-grade phishing simulations for a flat $9/month per MSP tenant.</p><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 24px;">No seat counting. No surprise bills. Unlimited users.</p><a href="https://www.phishsimai.com" style="display:inline-block;background:#0066cc;color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:600;">Start your 14-day trial</a></td></tr><tr><td style="padding:20px 40px 40px;border-top:1px solid #eee;font-size:12px;color:#666;">PhishSimAI | <a href="https://www.phishsimai.com/unsubscribe" style="color:#666;">Unsubscribe</a></td></tr></table></td></tr></table></body></html>`
  },
  {
    subject: "How [Company] can cut phishing clicks by 41%",
    htmlBody: `<!DOCTYPE html><html><body style="margin:0;padding:0;font-family:Arial,sans-serif;background:#f4f4f4;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;margin:20px auto;border-radius:8px;"><tr><td style="padding:40px 40px 20px;"><h2 style="color:#1a1a1a;font-size:22px;margin:0 0 20px;">Hi [FirstName],</h2><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px;">MSPs using PhishSimAI report an average 41% reduction in click rates within 90 days.</p><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 24px;">Our AI-generated scenarios adapt to your clients' industries and keep training relevant.</p><a href="https://www.phishsimai.com" style="display:inline-block;background:#0066cc;color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:600;">See the results</a></td></tr><tr><td style="padding:20px 40px 40px;border-top:1px solid #eee;font-size:12px;color:#666;">PhishSimAI | <a href="https://www.phishsimai.com/unsubscribe" style="color:#666;">Unsubscribe</a></td></tr></table></td></tr></table></body></html>`
  },
  {
    subject: "HIPAA one-click compliance reports for your clients",
    htmlBody: `<!DOCTYPE html><html><body style="margin:0;padding:0;font-family:Arial,sans-serif;background:#f4f4f4;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;margin:20px auto;border-radius:8px;"><tr><td style="padding:40px 40px 20px;"><h2 style="color:#1a1a1a;font-size:22px;margin:0 0 20px;">Hi [FirstName],</h2><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px;">[Company] clients in healthcare need defensible HIPAA training records. PhishSimAI generates audit-ready reports with one click.</p><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 24px;">Track completion, failures, and remediation automatically.</p><a href="https://www.phishsimai.com" style="display:inline-block;background:#0066cc;color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:600;">Generate sample report</a></td></tr><tr><td style="padding:20px 40px 40px;border-top:1px solid #eee;font-size:12px;color:#666;">PhishSimAI | <a href="https://www.phishsimai.com/unsubscribe" style="color:#666;">Unsubscribe</a></td></tr></table></td></tr></table></body></html>`
  },
  {
    subject: "SOC 2 audit evidence in minutes, not days",
    htmlBody: `<!DOCTYPE html><html><body style="margin:0;padding:0;font-family:Arial,sans-serif;background:#f4f4f4;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;margin:20px auto;border-radius:8px;"><tr><td style="padding:40px 40px 20px;"><h2 style="color:#1a1a1a;font-size:22px;margin:0 0 20px;">Hi [FirstName],</h2><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px;">SOC 2 auditors want proof of ongoing security awareness. PhishSimAI exports timestamped completion logs and failure trends instantly.</p><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 24px;">Save hours during every audit cycle.</p><a href="https://www.phishsimai.com" style="display:inline-block;background:#0066cc;color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:600;">Try it now</a></td></tr><tr><td style="padding:20px 40px 40px;border-top:1px solid #eee;font-size:12px;color:#666;">PhishSimAI | <a href="https://www.phishsimai.com/unsubscribe" style="color:#666;">Unsubscribe</a></td></tr></table></td></tr></table></body></html>`
  },
  {
    subject: "CMMC 2.0 just became mandatory. Are you ready?",
    htmlBody: `<!DOCTYPE html><html><body style="margin:0;padding:0;font-family:Arial,sans-serif;background:#f4f4f4;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;margin:20px auto;border-radius:8px;"><tr><td style="padding:40px 40px 20px;"><h2 style="color:#1a1a1a;font-size:22px;margin:0 0 20px;">Hi [FirstName],</h2><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px;">CMMC 2.0 Level 1 requires documented security awareness training. PhishSimAI gives defense contractors and their MSPs automated, audit-ready records.</p><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 24px;">Stay ahead of DoD requirements.</p><a href="https://www.phishsimai.com" style="display:inline-block;background:#0066cc;color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:600;">Get CMMC-ready</a></td></tr><tr><td style="padding:20px 40px 40px;border-top:1px solid #eee;font-size:12px;color:#666;">PhishSimAI | <a href="https://www.phishsimai.com/unsubscribe" style="color:#666;">Unsubscribe</a></td></tr></table></td></tr></table></body></html>`
  },
  {
    subject: "What's your current phishing training ROI?",
    htmlBody: `<!DOCTYPE html><html><body style="margin:0;padding:0;font-family:Arial,sans-serif;background:#f4f4f4;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;margin:20px auto;border-radius:8px;"><tr><td style="padding:40px 40px 20px;"><h2 style="color:#1a1a1a;font-size:22px;margin:0 0 20px;">Hi [FirstName],</h2><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px;">Most MSPs can't quantify the ROI of their security awareness program. PhishSimAI shows click-rate reduction, time saved on audits, and risk reduction per client.</p><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 24px;">See your numbers in real time.</p><a href="https://www.phishsimai.com" style="display:inline-block;background:#0066cc;color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:600;">Calculate ROI</a></td></tr><tr><td style="padding:20px 40px 40px;border-top:1px solid #eee;font-size:12px;color:#666;">PhishSimAI | <a href="https://www.phishsimai.com/unsubscribe" style="color:#666;">Unsubscribe</a></td></tr></table></td></tr></table></body></html>`
  },
  {
    subject: "Following up on phishing training for [Company]",
    htmlBody: `<!DOCTYPE html><html><body style="margin:0;padding:0;font-family:Arial,sans-serif;background:#f4f4f4;"><table width="100%" cellpadding="0" cellspacing="0"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;margin:20px auto;border-radius:8px;"><tr><td style="padding:40px 40px 20px;"><h2 style="color:#1a1a1a;font-size:22px;margin:0 0 20px;">Hi [FirstName],</h2><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px;">I haven't heard back, so I'll keep this short. If PhishSimAI isn't the right fit for [Company] right now, no hard feelings.</p><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 16px;">If it is, the 14-day trial is still open at https://www.phishsimai.com.</p><p style="color:#333;font-size:16px;line-height:1.6;margin:0 0 24px;">Either way, thanks for your time.</p><a href="https://www.phishsimai.com" style="display:inline-block;background:#0066cc;color:#ffffff;padding:12px 28px;text-decoration:none;border-radius:6px;font-weight:600;">Start trial</a></td></tr><tr><td style="padding:20px 40px 40px;border-top:1px solid #eee;font-size:12px;color:#666;">PhishSimAI | <a href="https://www.phishsimai.com/unsubscribe" style="color:#666;">Unsubscribe</a></td></tr></table></td></tr></table></body></html>`
  }
];